[package]
name = "pact_verifier_cli"
version = "0.8.1"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2018"
description = "Standalone pact verifier for provider pact verification"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_verifier_cli"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
libc = "0.2.76"
clap = "2.33.0"
pact_matching = { version = "0.7.0", path = "../pact_matching" }
pact_verifier = { version = "0.9.0", path = "../pact_verifier" }
simplelog = "0.8"
log = "0.4.8"
maplit = "1.0.2"
lazy_static = "1.4.0"
rand = "0.7.3"
regex = "1.3.9"
tokio = { version = "0.2.9", features = ["rt-core", "macros"] }

[dev-dependencies]
quickcheck = "0.9.2"
expectest = "0.12.0"
