[package]
name = "pact_mock_server"
version = "0.7.1"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2018"
description = "Pact-Rust support library that implements in process mock server"
documentation = "https://docs.rs/pact_mock_server/0.4.2/pact_mock_server/"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_mock_server"
readme = "README.md"
keywords = ["testing", "pact", "cdc", "mockserver"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
serde_json = "1.0"
pact_matching = { version =  "0.5.10", path = "../pact_matching" }
log = "0.4.8"
maplit = "0.1.4"
lazy_static = "1.4.0"
uuid = { version = "0.6", features = ["v4"] }
itertools = "0.6.1"
tokio = { version = "0.2.9", features = ["rt-threaded", "macros"] }
futures = "0.3"
hyper = "0.13"
bytes = "0.5"

[dev-dependencies]
quickcheck = "0.4.1"
expectest = "0.9.1"
