[package]
name = "pact_mock_server_cli"
version = "0.7.1"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2018"
description = "Standalone pact mock server for consumer pact tests"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_mock_server_cli"
readme = "README.md"
keywords = ["testing", "pact", "cdc", "mockserver"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
libc = "0.2.9"
clap = "2.31.2"
serde_json = "1.0"
pact_matching = { version = "0.7.1", path = "../pact_matching" }
pact_mock_server = { version = "0.7.5", path = "../pact_mock_server" }
simplelog = "^0.7"
log = "0.4"
uuid = { version = "0.8", features = ["v4"] }
maplit = "0.1.3"
rand = "0.4.2"
webmachine-rust = "0.2.0"
regex = "0.1"
lazy_static = "1.4.0"
reqwest = { version = "0.10", features = ["json"] }
url = "2.1.1"
http = "0.2.1"
futures = "0.3.0"
tokio = { version = "0.2.9", features = ["rt-threaded", "macros", "blocking"] }
hyper = "0.13.0"

[dev-dependencies]
quickcheck = "0.2"
expectest = "0.5.1"
