[package]
name = "pact_matching"
version = "0.5.7"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
description = "Pact-Rust support library that implements request and response matching logic"
documentation = "https://docs.rs/pact_matching/0.5.7/pact_matching/"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_matching"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
serde = "1.0.11"
serde_json = "1.0.2"
serde_derive = "1.0.11"
hex = "0.2.0"
log = "0.3.8"
onig = "5.0.0"
maplit = "0.1.4"
lazy_static = "0.2.8"
semver = "0.7.0"
itertools = "0.8.0"
rand = "0.6"
sxd-document = "0.2.4"
ansi_term = "0.9.0"
difference = "1.0.0"
base64 = "0.7.0"
uuid = { version = "0.5.1", features = ["v4"] }
indextree = "1.1.1"
nom = "^4.0"
chrono = "0.4"
chrono-tz = "0.4"
rand_regex = "0.12.0"
regex-syntax = "0.6.4"
reqwest = "0.9.19"

[dev-dependencies]
quickcheck = "0.4.1"
expectest = "0.11.0"
env_logger = "0.4.3"
hamcrest2 = "0.2.6"
