[package]
name = "pact_matching"
version = "0.6.2"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2018"
description = "Pact-Rust support library that implements request and response matching logic"
documentation = "https://docs.rs/pact_matching/0.5.15/pact_matching/"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_matching"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
hex = "0.2.0"
log = "0.4"
onig = "4.3.3"
maplit = "0.1.4"
lazy_static = "1.4.0"
semver = "0.7.0"
itertools = "0.9.0"
rand = "0.6"
sxd-document = "0.3.2"
ansi_term = "0.9.0"
difference = "1.0.0"
base64 = "0.12.0"
uuid = { version = "0.5.1", features = ["v4"] }
indextree = "1.1.1"
nom = "^4.0"
chrono = "0.4"
chrono-tz = "0.4"
rand_regex = "0.12.0"
regex-syntax = "0.6.4"
tree_magic = "0.2.3"
formdata = "0.12.3"
hyper = "0.10"
httparse = "1.0"
mime = "0.2.6"

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["rustls-tls", "blocking", "json"]

[dev-dependencies]
quickcheck = "0.9.2"
expectest = "0.12.0"
env_logger = "0.7.1"
hamcrest2 = "0.3.0"
speculate = "0.1"
test-env-log = "0.2.2"
ntest = "0.7.1"
