[package]
name = "pact_verifier"
version = "0.6.1"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
description = "Pact-Rust support library that implements provider verification functions"
documentation = "https://docs.rs/pact_verifier/0.6.1/pact_verifier/"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_verifier"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
libc = "0.2.9"
serde_json = "1.0"
pact_matching = { version = "0.5.4", path = "../pact_matching" }
p-macro = "0.2.0"
log = "0.3.8"
maplit = "0.1.3"
lazy_static = "0.1.15"
itertools = "0.8.0"
ansi_term = "0.9"
regex = "0.1"
difference = "0.4"
tokio = "0.1.22"
futures = "0.1"
hyper = "0.12"
reqwest = "0.9.19"
mime = "0.3"
bytes = "0.4.4"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
quickcheck = "0.2"
expectest = "0.5.1"
env_logger = "0.3.2"
http = "0.1"
pact_consumer = { version = "0.5.1", path = "../pact_consumer" }
