[package]
name = "pact_verifier"
version = "0.7.0"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2018"
description = "Pact-Rust support library that implements provider verification functions"
documentation = "https://docs.rs/pact_verifier/0.6.2/pact_verifier/"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_verifier"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
libc = "0.2.9"
serde_json = "1.0"
pact_matching = { version = "0.5.8", path = "../pact_matching" }
log = "0.4"
maplit = "0.1.3"
lazy_static = "0.1.15"
itertools = "0.8.0"
ansi_term = "0.9"
regex = "1.3.1"
difference = "0.4"
futures = "0.3"
hyper = "0.13"
reqwest = { version = "0.10", features = ["blocking", "json"] }
mime = "0.3"
bytes = "0.5"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
tokio = { version = "0.2.9", features = ["rt-core", "macros"] }
quickcheck = "0.2"
expectest = "0.5.1"
env_logger = "0.3.2"
http = "0.2"
pact_consumer = { version = "0.6.0", path = "../pact_consumer" }
