[package]
name = "pact_models"
version = "0.0.1"
authors = ["Ronald Holshausen <rholshausen@dius.com.au>"]
edition = "2018"
description = "Pact-Rust support library that provides the core models for dealing with Pact files"
documentation = "https://docs.rs/pact_models/0.0.1/pact_models/"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_models"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
