[package]
name = "pact_mock_server_ffi"
version = "0.0.0"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
description = "Pact mock server interface for foreign languages"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_mock_server_ffi"
readme = "README.md"
keywords = ["testing", "pact", "cdc", "mockserver"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
pact_matching = { version = "0.5.3", path = "../pact_matching" }
pact_mock_server = { version = "0.6.0", path = "../pact_mock_server" }

[dev-dependencies]
expectest = "0.5.1"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]
